name: 'flutter_demo'
publish_to: none

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  canvas_ui:
    path: ../canvas_ui
  flutter:
    path: ../flutter
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
