name: 'canvas_ui'
version: 0.0.1-alpha.1
description: canvas_ui
authors:
- Benjamin Strauß <benmastra@gmail.com>
homepage: https://github.com/b-strauss/canvas_ui
publish_to: none

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
